[package]
name = "coffee_machine"
version = "0.1.0"
edition = "2021"

[build]
target = "armv7-unknown-linux-gnueabihf"

[target.armv7-unknown-linux-gnueabihf]
linker = "armv7-unknown-linux-gnueabihf-gcc"

[dependencies]
